[workspace]
members = ["abstract-account-contract", "auth-contracts/webauthn-auth-contract"]

[workspace.dependencies]
near-sdk = "5.5.0"
p256 = "0.13.2"
sha2 = "0.10.8"
hex = "0.4.3"
getrandom = { version = "0.2", features = ["js"] }
schemars = "0.8.21"
