[workspace]
members = [
  "abstract-account",
  "interfaces",
  "auth/webauthn-auth",
  "auth/ethereum-auth",
]

[workspace.dependencies]
near-sdk = "5.5.0"
p256 = "0.13.2"
sha2 = "0.10.8"
hex = "0.4.3"
schemars = "0.8.21"
sha3 = "0.10.8"
secp256k1 = { version = "0.30.0", features = ["recover"] }
